In [69]:
import os
import sxs
import qnm
from kuibit.timeseries import TimeSeries as kuibit_ts
import sys
sys.path.append("..")
import gen_utils
import numpy as np
import BOB_utils
import gen_utils

In [63]:
cache_path = os.path.join(os.getcwd(), "sxs_cache")
sxs.write_config(cache_directory=cache_path)

# Now, when you call load, it will use this path
# catalog = sxs.load("catalog", download = False)

In [16]:
# test_sims = (
sim = sxs.load("SXS:BBH:1832",download=False)

In [25]:
sim.psi4

WaveformModes([[-1.51458292e-04+3.48199172e-04j, -5.39068261e-05+2.38872714e-04j,
         1.31339908e-05+3.49157986e-04j, ...,
         1.91395771e-05-2.77127650e-05j,  7.65399732e-06-1.93602512e-05j,
        -3.30161838e-05+3.47232325e-05j],
       [-7.58087626e-05+4.14673106e-04j, -6.17528222e-05+2.53518784e-04j,
         1.92170585e-05+2.59033621e-04j, ...,
         1.74684955e-05-2.56085875e-05j,  1.81942068e-05-9.99844023e-09j,
        -4.99048375e-05+2.87528911e-05j],
       [ 4.52924632e-05+4.32800875e-04j, -5.44489009e-05+2.36073200e-04j,
        -3.35589802e-05+1.35291723e-04j, ...,
         1.18550348e-05-2.04316372e-05j,  2.64572287e-05+2.57943488e-05j,
        -6.47263898e-05+1.69152511e-05j],
       ...,
       [ 1.78745759e-06-5.72743520e-07j, -8.49353952e-07-8.86814857e-07j,
        -5.33967785e-07+4.26076222e-08j, ...,
         3.14709017e-10-1.94713380e-10j,  1.94505338e-10+2.50696065e-10j,
         5.02871056e-10+4.46587136e-10j],
       [ 1.80422824e-06-4.61938462e-

In [19]:
sim.psi4

  0%|                                                                               | 0/491 [00:00<?, ?it/s]

  0%|                                                                          | 0/33855407 [00:00<?, ?it/s]

WaveformModes([[-1.51458292e-04+3.48199172e-04j, -5.39068261e-05+2.38872714e-04j,
         1.31339908e-05+3.49157986e-04j, ...,
         1.91395771e-05-2.77127650e-05j,  7.65399732e-06-1.93602512e-05j,
        -3.30161838e-05+3.47232325e-05j],
       [-7.58087626e-05+4.14673106e-04j, -6.17528222e-05+2.53518784e-04j,
         1.92170585e-05+2.59033621e-04j, ...,
         1.74684955e-05-2.56085875e-05j,  1.81942068e-05-9.99844023e-09j,
        -4.99048375e-05+2.87528911e-05j],
       [ 4.52924632e-05+4.32800875e-04j, -5.44489009e-05+2.36073200e-04j,
        -3.35589802e-05+1.35291723e-04j, ...,
         1.18550348e-05-2.04316372e-05j,  2.64572287e-05+2.57943488e-05j,
        -6.47263898e-05+1.69152511e-05j],
       ...,
       [ 1.78745759e-06-5.72743520e-07j, -8.49353952e-07-8.86814857e-07j,
        -5.33967785e-07+4.26076222e-08j, ...,
         3.14709017e-10-1.94713380e-10j,  1.94505338e-10+2.50696065e-10j,
         5.02871056e-10+4.46587136e-10j],
       [ 1.80422824e-06-4.61938462e-

In [26]:
sim2 = sxs.load("SXS:BBH:1234",download=False)

In [27]:
sim2.news

AttributeError: 'Simulation_v3' object has no attribute 'news'

## 09/29

In [101]:
def kuibit_ts_save(timeseries, location):
    # timeseries is an dictionary of kuibit timeseries
    # location is the relative path
    arrays_to_save = {}
    for name, ts in timeseries.items():
        # Store both time and data arrays under unique keys
        arrays_to_save[f"{name}_t"] = ts.t
        arrays_to_save[f"{name}_y"] = ts.y
    np.savez(location, **arrays_to_save)
    return 
def kuibit_ts_load(location):
    data = np.load(location)
    timeseries = {}
    for key in data.files:
        if key.endswith("_t"):
            name = key[:-2]
            t = data[f"{name}_t"]
            y = data[f"{name}_y"]
            timeseries[name] = kuibit_ts(t, y)
    return timeseries

In [ ]:
BOB = BOB_utils.BOB()
BOB.initialize_with_NR_psi4_data(t = ts_psi4.t, y = ts_psi4.y, mf = 0.949435238357, chif = (-1.10929877907e-08,
        3.32552069179e-09,
        0.678561988326))
BOB.what_should_BOB_create = "psi4"
BOB.optimize_Omega0_and_Phi0 = True

In [35]:
BOB = BOB_utils.BOB()
BOB.initialize_with_sxs_data("SXS:BBH:2325",l=2,m=2,download=False)
BOB.what_should_BOB_create = "psi4"
BOB.optimize_Omega0_and_Phi0 = True

Destination path /home/chrosmic/.cache/qnm/data-0.4.0.tar.bz2 already exists, use overwrite=True to force an overwrite.
loading SXS data:  SXS:BBH:2325


  0%|                                                                               | 0/491 [00:00<?, ?it/s]

  0%|                                                                          | 0/23450282 [00:00<?, ?it/s]

In [137]:
BOB.what_should_BOB_create = "psi4"
BOB.optimize_Omega0_and_Phi0 = True
t_bob_psi4, y_bob_psi4 = BOB.construct_BOB()
ts_2325_psi4 = kuibit_ts(t_bob_psi4, y_bob_psi4)
mismatch(ts_2325_psi4, ts_2325_psi4)

0.0

In [118]:
y_bob_psi4

array([-1.31698067e-04-0.00129217j, -1.58106444e-04-0.00130043j,
       -1.84898115e-04-0.00130824j, ...,  5.46327696e-05-0.0001477j ,
        4.59838810e-05-0.00014922j,  3.73385416e-05-0.00015024j])

In [138]:
BOB.what_should_BOB_create = "news"
BOB.optimize_Omega0_and_Phi0 = True
t_bob_news, y_bob_news = BOB.construct_BOB()
ts_2325_news= kuibit_ts(t_bob_news, y_bob_news)
mismatch(ts_2325_news, ts_2325_news)

6.514008639625605e-17

In [139]:
BOB.what_should_BOB_create = "strain"
BOB.optimize_Omega0_and_Phi0 = True
t_bob_strain, y_bob_strain = BOB.construct_BOB()
ts_2325_strain= kuibit_ts(t_bob_strain, y_bob_strain)
mismatch(ts_2325_strain, ts_2325_strain)

5.0144781282160135e-17

In [140]:
np.abs(mismatch(ts_2325_strain, ts_2325_psi4))

0.31407442926984364

In [117]:
y_bob_strain

array([-1.31698067e-04-0.00129217j, -1.58106444e-04-0.00130043j,
       -1.84898115e-04-0.00130824j, ...,  5.46327696e-05-0.0001477j ,
        4.59838810e-05-0.00014922j,  3.73385416e-05-0.00015024j])

In [128]:
timeseries_2325 = {
    "psi4": ts_2325_psi4,
    "news": ts_2325_news,
    "strain": ts_2325_strain
}

In [129]:
kuibit_ts_save(timeseries_2325, "trusted_outputs/BBH_2325_BOB_wf.npz")

In [133]:
BOB_exp = kuibit_ts_load("trusted_outputs/BBH_2325_BOB_wf.npz")

In [136]:
BOB_exp["psi4"]


In [37]:
BOB.Ap

0.07376514659678879

In [60]:
location = "trusted_outputs/BOB_BBH_2325_optimize_psi4.npz"
def save_bob_attributes(BOB, filename):
    """
    Save the physically important BOB parameters to a .npz file.
    """
    attrs_to_save = {
        "mf": BOB.mf,
        "chif": np.array(BOB.chif),
        "l": BOB.l,
        "m": BOB.m,
        "Ap": BOB.Ap,
        "tp": BOB.tp,
        "Omega_0": BOB.Omega_0,
        "Phi_0": BOB.Phi_0,
        "tau": BOB.tau,
        "Omega_ISCO": BOB.Omega_ISCO,
        "what_should_BOB_create": getattr(BOB, "what_should_BOB_create", None),
        "optimize_Omega0_and_Phi0": getattr(BOB, "optimize_Omega0_and_Phi0", None),
    }

    np.savez(filename, **attrs_to_save)
    print(f"[INFO] Saved BOB parameters to {filename}")


In [61]:
save_bob_attributes(BOB, location)

[INFO] Saved BOB parameters to trusted_outputs/BOB_BBH_2325_optimize_psi4.npz


In [49]:
data = np.load(location)
print(data["mf"], data["chif"], data["Omega_0"])

0.9516113621985476 0.6864407656228295 0.1478517174758218


In [126]:
def mismatch(ts1, ts2, t0=None, tf=None):

    # Extract time and values from Kuibit TimeSeries
    t1, y1 = ts1.t, ts1.y
    t2, y2 = ts2.t, ts2.y

    # Ensure y-data is 1D
    y1 = np.atleast_1d(y1)
    y2 = np.atleast_1d(y2)

    # Determine default t0 and tf from overlap
    if t0 is None:
        t0 = max(t1[0], t2[0])
    if tf is None:
        tf = min(t1[-1], t2[-1])

    if t0 >= tf:
        raise ValueError("No overlapping time interval between the two series.")

    # Common time grid
    dt = min(np.min(np.diff(t1)), np.min(np.diff(t2)))
    common_t = np.arange(t0, tf, dt)

    # Interpolate both waveforms
    y1_interp = np.interp(common_t, t1, y1)
    y2_interp = np.interp(common_t, t2, y2)

    # Inner product helper
    def inner_product(a, b):
        return np.trapz(a * b, common_t)

    # Compute normalized overlap
    overlap = inner_product(y1_interp, y2_interp)
    norm1 = np.sqrt(inner_product(y1_interp, y1_interp))
    norm2 = np.sqrt(inner_product(y2_interp, y2_interp))

    if norm1 == 0 or norm2 == 0:
        raise ValueError("One of the waveforms has zero norm.")

    return np.abs(1 - overlap / (norm1 * norm2))


In [65]:
BOB2 = BOB_utils.BOB()
BOB2.initialize_with_cce_data(1)
BOB2.what_should_BOB_create = "news"
BOB2.optimize_Omega0_and_Phi0 = False

Destination path /home/chrosmic/.cache/qnm/data-0.4.0.tar.bz2 already exists, use overwrite=True to force an overwrite.
loading CCE data


In [97]:
t_bob_cce, y_bob_cce = BOB2.construct_BOB()
ts_cce = kuibit_ts(t_bob_cce, y_bob_cce)
mismatch(ts_cce, ts_cce)

In [99]:
print(mismatch(ts_cce, ts_cce, t0 = t_bob_cce[0], tf = t_bob_cce[-1]))

8.111802055638745e-17j


In [76]:
t_bob_cce

array([5923.66195533, 5923.76195533, 5923.86195533, ..., 6098.36195533,
       6098.46195533, 6098.56195533])

In [68]:
save_bob_attributes(BOB2, "trusted_outputs/BOB_CCE1_news.npz")

[INFO] Saved BOB parameters to trusted_outputs/BOB_CCE1_news.npz
